2025-03-01 19:08:03,474 INFO: Starting vLLM server for model at '/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M' on port 8000...
2025-03-01 19:08:03,479 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f98a946c830>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 19:08:03,479 INFO: Starting server for model at '/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M' on port 8000 with command: python -m vllm.entrypoints.openai.api_server --model /HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M --port 8000
2025-03-01 19:08:26,241 INFO: INFO 03-01 19:08:09 __init__.py:207] Automatically detected platform cuda.
2025-03-01 19:08:26,241 ERROR: 
2025-03-01 19:08:26,241 INFO: INFO 03-01 19:08:09 api_server.py:912] vLLM API server version 0.7.3
2025-03-01 19:08:26,243 ERROR: Loading safetensors checkpoint shards:   0% Completed | 0/8 [00:00<?, ?it/s]
2025-03-01 19:08:27,055 INFO: INFO 03-01 19:08:09 api_server.py:913] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
2025-03-01 19:08:27,055 ERROR: 
2025-03-01 19:08:27,057 INFO: INFO 03-01 19:08:09 api_server.py:209] Started engine process with PID 2883384
2025-03-01 19:08:27,057 ERROR: Loading safetensors checkpoint shards:  12% Completed | 1/8 [00:00<00:05,  1.23it/s]
2025-03-01 19:08:28,314 INFO: INFO 03-01 19:08:15 __init__.py:207] Automatically detected platform cuda.
2025-03-01 19:08:28,314 ERROR: 
2025-03-01 19:08:28,314 INFO: INFO 03-01 19:08:17 config.py:549] This model supports multiple tasks: {'generate', 'reward', 'embed', 'score', 'classify'}. Defaulting to 'generate'.
2025-03-01 19:08:28,314 ERROR: Loading safetensors checkpoint shards:  25% Completed | 2/8 [00:02<00:06,  1.08s/it]2025-03-01 19:08:34,137 INFO: WARNING 03-01 19:08:07 arg_utils.py:1187] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
2025-03-01 19:08:34,138 ERROR: 
2025-03-01 19:08:34,138 INFO: INFO 03-01 19:08:07 config.py:1555] Chunked prefill is enabled with max_num_batched_tokens=2048.
2025-03-01 19:08:34,139 ERROR: Loading safetensors checkpoint shards:  38% Completed | 3/8 [00:15<00:32,  6.44s/it]
2025-03-01 19:08:35,166 INFO: INFO 03-01 19:08:15 config.py:549] This model supports multiple tasks: {'embed', 'generate', 'reward', 'classify', 'score'}. Defaulting to 'generate'.
2025-03-01 19:08:35,166 ERROR: 
2025-03-01 19:08:35,167 INFO: WARNING 03-01 19:08:15 arg_utils.py:1187] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
2025-03-01 19:08:35,168 ERROR: Loading safetensors checkpoint shards:  50% Completed | 4/8 [00:16<00:17,  4.30s/it]
2025-03-01 19:08:36,419 INFO: INFO 03-01 19:08:15 config.py:1555] Chunked prefill is enabled with max_num_batched_tokens=2048.
2025-03-01 19:08:36,419 ERROR: 
2025-03-01 19:08:36,419 INFO: INFO 03-01 19:08:15 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.3) with config: model='/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M', speculative_config=None, tokenizer='/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1010000, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True,
2025-03-01 19:08:36,421 ERROR: Loading safetensors checkpoint shards:  62% Completed | 5/8 [00:17<00:09,  3.20s/it]
2025-03-01 19:08:37,412 INFO: INFO 03-01 19:08:18 cuda.py:229] Using Flash Attention backend.
2025-03-01 19:08:37,412 ERROR: 
2025-03-01 19:08:37,412 INFO: INFO 03-01 19:08:18 model_runner.py:1110] Starting to load model /HSC/users/hogade/huggingface_models/Qwen2.5-14B-Instruct-1M...
2025-03-01 19:08:37,412 ERROR: Loading safetensors checkpoint shards:  75% Completed | 6/8 [00:18<00:04,  2.45s/it]
2025-03-01 19:08:39,497 INFO: INFO 03-01 19:08:39 model_runner.py:1115] Loading model weights took 27.7981 GB
2025-03-01 19:08:39,497 ERROR: 
2025-03-01 19:08:40,466 INFO: INFO 03-01 19:08:40 worker.py:267] Memory profiling takes 0.76 seconds
2025-03-01 19:08:40,466 ERROR: Loading safetensors checkpoint shards:  88% Completed | 7/8 [00:19<00:01,  1.97s/it]
2025-03-01 19:08:40,466 INFO: INFO 03-01 19:08:40 worker.py:267] the current vLLM instance can use total_gpu_memory (79.26GiB) x gpu_memory_utilization (0.90) = 71.33GiB
2025-03-01 19:08:40,466 ERROR: 
2025-03-01 19:08:40,468 INFO: INFO 03-01 19:08:40 worker.py:267] model weights take 27.80GiB; non_torch_memory takes 0.09GiB; PyTorch activation peak memory takes 1.41GiB; the rest of the memory reserved for KV Cache is 42.03GiB.
2025-03-01 19:08:40,468 ERROR: Loading safetensors checkpoint shards: 100% Completed | 8/8 [00:20<00:00,  1.55s/it]
2025-03-01 19:08:40,713 INFO: INFO 03-01 19:08:40 executor_base.py:111] # cuda blocks: 14347, # CPU blocks: 1365
2025-03-01 19:08:40,713 ERROR: 
2025-03-01 19:08:40,713 INFO: INFO 03-01 19:08:40 executor_base.py:116] Maximum concurrency for 1010000 tokens per request: 0.23x
2025-03-01 19:08:40,714 ERROR: Loading safetensors checkpoint shards: 100% Completed | 8/8 [00:20<00:00,  2.50s/it]
2025-03-01 19:08:40,714 INFO: ERROR 03-01 19:08:40 engine.py:400] The model's max seq len (1010000) is larger than the maximum number of tokens that can be stored in KV cache (229552). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
2025-03-01 19:08:40,715 ERROR: 
2025-03-01 19:08:40,715 INFO: ERROR 03-01 19:08:40 engine.py:400] Traceback (most recent call last):
2025-03-01 19:08:40,715 ERROR: Process SpawnProcess-1:
2025-03-01 19:08:40,715 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 391, in run_mp_engine
2025-03-01 19:08:40,715 ERROR: Traceback (most recent call last):
2025-03-01 19:08:40,715 INFO: ERROR 03-01 19:08:40 engine.py:400]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
2025-03-01 19:08:40,715 ERROR: File "/home/hogade/.local/share/uv/python/cpython-3.12.9-linux-x86_64-gnu/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
2025-03-01 19:08:40,715 INFO: ERROR 03-01 19:08:40 engine.py:400]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,716 ERROR: self.run()
2025-03-01 19:08:40,716 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 124, in from_engine_args
2025-03-01 19:08:40,716 ERROR: File "/home/hogade/.local/share/uv/python/cpython-3.12.9-linux-x86_64-gnu/lib/python3.12/multiprocessing/process.py", line 108, in run
2025-03-01 19:08:40,716 INFO: ERROR 03-01 19:08:40 engine.py:400]     return cls(ipc_path=ipc_path,
2025-03-01 19:08:40,716 ERROR: self._target(*self._args, **self._kwargs)
2025-03-01 19:08:40,716 INFO: ERROR 03-01 19:08:40 engine.py:400]            ^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,717 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 402, in run_mp_engine
2025-03-01 19:08:40,717 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 76, in __init__
2025-03-01 19:08:40,717 ERROR: raise e
2025-03-01 19:08:40,717 INFO: ERROR 03-01 19:08:40 engine.py:400]     self.engine = LLMEngine(*args, **kwargs)
2025-03-01 19:08:40,717 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 391, in run_mp_engine
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,718 ERROR: engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 276, in __init__
2025-03-01 19:08:40,718 ERROR: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]     self._initialize_kv_caches()
2025-03-01 19:08:40,718 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 124, in from_engine_args
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 434, in _initialize_kv_caches
2025-03-01 19:08:40,718 ERROR: return cls(ipc_path=ipc_path,
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
2025-03-01 19:08:40,718 ERROR: ^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,718 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 122, in initialize_cache
2025-03-01 19:08:40,719 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 76, in __init__
2025-03-01 19:08:40,720 INFO: ERROR 03-01 19:08:40 engine.py:400]     self.collective_rpc("initialize_cache",
2025-03-01 19:08:40,720 ERROR: self.engine = LLMEngine(*args, **kwargs)
2025-03-01 19:08:40,720 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
2025-03-01 19:08:40,720 ERROR: ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,720 INFO: ERROR 03-01 19:08:40 engine.py:400]     answer = run_method(self.driver_worker, method, args, kwargs)
2025-03-01 19:08:40,720 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 276, in __init__
2025-03-01 19:08:40,720 INFO: ERROR 03-01 19:08:40 engine.py:400]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,720 ERROR: self._initialize_kv_caches()
2025-03-01 19:08:40,721 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/utils.py", line 2196, in run_method
2025-03-01 19:08:40,722 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 434, in _initialize_kv_caches
2025-03-01 19:08:40,722 INFO: ERROR 03-01 19:08:40 engine.py:400]     return func(*args, **kwargs)
2025-03-01 19:08:40,722 ERROR: self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
2025-03-01 19:08:40,722 INFO: ERROR 03-01 19:08:40 engine.py:400]            ^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,722 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 122, in initialize_cache
2025-03-01 19:08:40,722 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/worker/worker.py", line 291, in initialize_cache
2025-03-01 19:08:40,722 ERROR: self.collective_rpc("initialize_cache",
2025-03-01 19:08:40,723 INFO: ERROR 03-01 19:08:40 engine.py:400]     raise_if_cache_size_invalid(num_gpu_blocks,
2025-03-01 19:08:40,723 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
2025-03-01 19:08:40,723 INFO: ERROR 03-01 19:08:40 engine.py:400]   File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/worker/worker.py", line 544, in raise_if_cache_size_invalid
2025-03-01 19:08:40,723 ERROR: answer = run_method(self.driver_worker, method, args, kwargs)
2025-03-01 19:08:40,723 INFO: ERROR 03-01 19:08:40 engine.py:400]     raise ValueError(
2025-03-01 19:08:40,723 ERROR: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 19:08:40,723 INFO: ERROR 03-01 19:08:40 engine.py:400] ValueError: The model's max seq len (1010000) is larger than the maximum number of tokens that can be stored in KV cache (229552). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
2025-03-01 19:08:40,725 ERROR: File "/home/hogade/vllm_env/lib/python3.12/site-packages/vllm/utils.py", line 2196, in run_method
2025-03-01 19:08:49,565 ERROR: return func(*args, **kwargs)
2025-03-01 19:08:49,567 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50f210b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 19:08:51,570 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50f211670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 19:08:53,573 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50f211d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 19:08:55,575 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50f1dbe60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-01 19:08:57,578 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe50f211be0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-02 03:08:49,052 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c587755e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-02 03:08:51,053 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c58774ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-02 03:08:53,056 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c58776cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-03-02 03:08:55,058 INFO: Server check on port 8000 failed: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c587775c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
